### ISSUE TITLE
LBCService stop working

### ISSUE THREAD

**Issue by xtrem007** [JooJooBee666/LBCService#7]
Lenovo has pushed an update to Keyboard_Core.dll and as a result LBCService not working anymore.
https://github.com/ligius-/lenovo-backlight-control/issues/5#issue-774117792

**Comment by JooJooBee666** [comment]
Updated the older branch and upload new installers.  It supports both the old and new DLL version now. https://github.com/JooJooBee666/LBCService/releases/tag/1.7.0.0
